// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
<<<<<<< HEAD:Migrations/20260430134232_InitialUserCreate.Designer.cs
using TaskFlowAPI.Data;
=======
using TaskFLowAPI.Data;
>>>>>>> dca66342fd571c4779676ca6b18eb7081b391d3e:Migrations/20260501140838_InitialUserCreate.Designer.cs

#nullable disable

namespace TaskFlowAPI.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20260501140838_InitialUserCreate")]
    partial class InitialUserCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<< HEAD:Migrations/20260430134232_InitialUserCreate.Designer.cs
            modelBuilder.Entity("TaskFlowAPI.Models.User", b =>
=======
            modelBuilder.Entity("TaskFLowAPI.Models.User", b =>
>>>>>>> dca66342fd571c4779676ca6b18eb7081b391d3e:Migrations/20260501140838_InitialUserCreate.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
